<?php

namespace app\common\controller;

use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //判断用户是否登录
        if (!session('?user')) {
            $this->redirect('/login/login/index');
        }

        $model_common = model('Common');
        $count = $model_common->notification_count();
        $this->assign('count',$count);

        $info = $model_common->notification_info();
        $this->assign('info',$info);

        $menu_info = $model_common->get_menu_info();
        $this->assign('menu_info',$menu_info);


        $module = request()->module();
        $controller = request()->controller();
        $action = request()->action();
        $menu_id = $model_common->get_menu_id($module,$controller,$action);
        $this->assign('menu_id_now',$menu_id);
    }

}